In [1]:
import random
import sys
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('../saved/ClassifyData.csv')

In [3]:
df

                                                   text Label
0     The food is definitely worth the wait!! We arr...  real
1     I've been to Upper Crust several times with my...  real
2     I love this place! I go there weekly for the w...  fake
3     Amazing food.  Fabulous service.  A bit off th...  real
4     Fresh food at a reasonable price. The veggie p...  fake
5     The staff was very kind and the food was great...  fake
6     Everything I have tried at Airobi a have to tr...  fake
7     Love this place!!! I love the food here! Some ...  fake
8     We had a reservation for 7 at 6 they had priva...  real
9     I eat here about once a week. Why? cause the p...  real
10    The BBQ is fabulous!!!!! It's definitely not b...  real
11    One of the best restaurants I have found since...  fake
12    Mashu Mashu has delicious falafels. Green insi...  real
13    Freshest sushi in Pittsburgh.  The staff is su...  real
14    Mothers Day Brunch was awesome from the lamb c...  real
15    This place is really good. Steak and chicken w...  fake
16    I seen this place for lunch, and I am not sure...  fake
17    This place is the best.  I eat here at least 3...  fake
18    This place is not to be missed.  The only thin...  fake
19    it is very romantic to be seated on the heated...  real
20    Are you looking for a place to shove a bunch o...  real
21    Amazing!!! One of the best sandwiches I've had...  real
22    The best pizza and salads around. Found them o...  fake
23    Absolutely delicious.  Moist kebabs the chicke...  real
24    This place is great. The ambience and customer...  fake
25    Came to Jared's for the first time. I got the ...  real
26    My favorite place for bubble tea. They have a ...  real
27    We always really enjoyed Tuckers. Driving by t...  real
28    Super friendly staff. I really love the atmosp...  fake
29    This place is amazing! Everything was great an...  fake
...                                                 ...   ...
2970  We really enjoyed Nacho Daddy. Food is awesome...  real
2971  Great place to go if you're looking for a grea...  real
2972  Wow this place was great. My girlfriend and I ...  real
2973  I loved the food and the ambience. Very friend...  fake
2974  Love this place and their service is great the...  fake
2975  The pizza here is fab! And the 2 people they h...  real
2976  I've been coming here for over 10 years. My fa...  fake
2977  I love their sushi this time (our server Teban...  fake
2978  Arrived at Spago in the Caesar's Forum Shops f...  real
2979  On my first day in Toronto with my wife, we ha...  real
2980  Great pizza, fun cupcakes, and the shrimp are ...  fake
2981  Reuben was the best bartender ever. Excellent ...  fake
2982  Great buns for the food not so hard to get bet...  fake
2983  This restaurant is one of the reasons why i'm ...  real
2984  I love this place so much i dont even care tha...  real
2985  Definitely lives up to its name of farm food g...  real
2986  Absolutely love this place! Super courteous an...  fake
2987  This place is amazing! The food is so good it ...  fake
2988  Just used Izzy and his awesome crew to Cater m...  real
2989  We had the shrimp rolls and the mulitany salad...  fake
2990  Awesome/Authentic Hawaiian shaved ice....My hu...  real
2991  This is a great place for a great Pho and grea...  fake
2992  This place is amazing! Great service and my fa...  fake
2993  Sat amas hooked.  Nice size portions.  Service...  fake
2994  This place is an awesome experience. I am plea...  fake
2995  Used to be Globe Cafe but let me tell you this...  real
2996  Not a sushi place for me. I am so glad we foun...  fake
2997  The food and service were amazing! French onio...  fake
2998  Great pizza, good atmosphere, and service was ...  real
2999  Food here is awesome and service is always goo...  fake

[3000 rows x 2 columns]

In [ ]:
## only need to run the following in the 1st run

In [2]:
# # read in the good reviews with total number = 1,500
# df_true = pd.read_csv('../notebook/five_star_restaurants_reviews_only.csv', header = None)
# df_true = df_true.sample(n=1500)
# df_true.columns = ["text"]

# #add the label for fake df
# df_true['Label'] = "real"

# len(df_true)

1500

In [3]:
# # read in the fake reviews with total number = 1,500
# df_fake1 = pd.read_csv('../saved/reviews_5star.txt', header=None)
# df_fake2 = pd.read_csv('../saved/reviews_5starv2.txt', header=None)
# df_fake3 = pd.read_csv('../saved/reviews_5starv3.txt', header=None)

# #concat the 3 txt
# df_fake = pd.concat([df_fake1, df_fake2, df_fake3])
# df_fake.columns = ["text"]

# #add the label for fake df
# df_fake['Label'] = "fake"

# len(df_fake)

1500

In [4]:
# # concatenate the true and fake reviews
# df = pd.concat([df_true, df_fake])

# # mix the reviews
# df = df.sample(n=3000)
# df = df.reset_index(drop=True)

In [5]:
# # remove <SOR> & <EOR>

# df['text'] = df['text'].str.replace("<SOR>", '')
# df['text'] = df['text'].str.replace("<EOR>", '')

In [13]:
# # df
# df.to_csv('../saved/ClassifyData.csv', index=False)

                                                   text Label
0     Our group arrived to the front of the Gold Spi...  real
1     Just had the most amazing Chinese restaurant i...  fake
2     Amazing brisket and brisket. Prices are small ...  fake
3     It was awesome. Pampered by the hostess, Mary....  real
4     Just had some amazing fish tacos.  The ingredi...  real
5     The food is amazing and the wait staff is very...  fake
6     I don't live in Arizona but I have been there ...  real
7     This was our first time eating here and we had...  fake
8     This is, hands-down, our favorite Indian resta...  real
9     Stopped in today for the filet with pesto saus...  fake
10    Great authentic Indian food. In Arizona I'd sa...  real
11    This place is a great place for sports and to ...  real
12    We had a wonderful food that past mes amazing ...  fake
13    I liked this place been searching for good bur...  fake
14    Great beer bar with a nice backyard beer garde...  real
15    Love love love this place!! Heidi j'lana Bahnc...  fake
16    This is my favorite downtown cafe. Not only do...  real
17    Good food and always a great time. Good place ...  fake
18    The Handlebar is definitely one of my favorite...  real
19    Great food, service and prices. I would recomm...  fake
20    This place never fails to impress. Every time ...  real
21    Amazing food, amazing service!  We definitely ...  fake
22    Very good service, friendly server, excellent ...  real
23    This place was the bomb.com this was the ice c...  fake
24    Really great food. A bit pricier than expected...  fake
25    Great food and my review was refulled.  The lo...  fake
26    This place was excellent. Portions were big, a...  fake
27    This place is a hidden gem that should not be ...  real
28    This is a great place for cheap take out sushi...  real
29    Great neighborhood place! Our waiter, Krysten ...  fake
...                                                 ...   ...
2970  Jamms is the Best Experience in the Summerlin ...  fake
2971  This place is off the hook. Excellent service,...  fake
2972  Jennifer and Amy were wonderful. Food was very...  fake
2973  Yummy!!! It is super confusing if it's your fi...  real
2974  I have been to both locations several times an...  real
2975  This place was awesome. Easy to find a seat, b...  fake
2976  Excellent service,  fantastic paella Patria an...  real
2977  What an outstanding little gem!!! My girlfrien...  real
2978  Absolutely the best pizza that I have had! I h...  real
2979  Amazing. Great bar back for breakfast. Food wa...  fake
2980  The service was great and we loved the outdoor...  real
2981  Delicious food, great atmosphere and the servi...  fake
2982  Great service, great food, and great atmospher...  fake
2983  The food is delicious and service is great. My...  fake
2984  Ordered takeout from Jen and they've all agree...  fake
2985  The food is great, service is excellent and th...  fake
2986  Best place for sashimi and absolutely deliciou...  fake
2987  Really cool atmosphere and the food is also wo...  fake
2988  There are a thousand excellent reviews of this...  real
2989  Great food, awesome people great service and v...  fake
2990  New Years Eve was perfect here. Fixed menu; $7...  real
2991  The owners are the sweetest people ever. We we...  real
2992  Loved this place! Our server, Katy, was really...  real
2993  What a HIDDEN GEM!! I loved the outdoor dining...  real
2994  We were staying at the Boulders resort which i...  real
2995  We had the tacos and the tomato basil soup. Th...  fake
2996  Best BBQ place in lakewood!! Great barbecue .....  fake
2997  BEST FOOD IN ARIZONA!!!! Worth every penny and...  real
2998  Amazing food!! Some of the best Italian that I...  real
2999  When I see this truck my mouth starts quiverI ...  real

[3000 rows x 2 columns]

In [4]:
# train, test, validation split

le = LabelEncoder()
le.fit(df['Label'])
allClasses = le.transform(df['Label'])
allFeatures = df.drop(['Label'], axis=1)

X_trainAndTest, X_validation, y_trainAndTest, y_validation = train_test_split(allFeatures, allClasses, test_size=0.20, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X_trainAndTest, y_trainAndTest, test_size=0.20, random_state=42)

In [6]:
# X_train

## 1.1 Number of Words

In [7]:
X_train['word_count'] = X_train['text'].apply(lambda x: len(str(x).split(" ")))
X_train.head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                                                   text  word_count
1221  The food is always good and reasonably priced....          30
1651  I am from NJ where I would enjoy pizza at leas...          72
1460  This place is great.  I love the ambiance (I'd...          60
1081  I never had bad service here but still going t...          32
1405  Great food, service and prices. I would recomm...          12

## 1.2 Number of Characters

In [8]:
X_train['char_count'] = X_train['text'].str.len() ## this also includes spaces
X_train.head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,text,word_count,char_count
1221,The food is always good and reasonably priced....,30,161
1651,I am from NJ where I would enjoy pizza at leas...,72,353
1460,This place is great. I love the ambiance (I'd...,60,316
1081,I never had bad service here but still going t...,32,185
1405,"Great food, service and prices. I would recomm...",12,71

## 1.3 Average Word Length

In [9]:
def avg_word(sentence):
  words = sentence.split()
  return (sum(len(word) for word in words)/len(words))

In [10]:
X_train['avg_word'] = X_train['text'].apply(lambda x: avg_word(x))
X_train.head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,text,word_count,char_count,avg_word
1221,The food is always good and reasonably priced....,30,161,4.400000
1651,I am from NJ where I would enjoy pizza at leas...,72,353,4.338462
1460,This place is great. I love the ambiance (I'd...,60,316,4.508772
1081,I never had bad service here but still going t...,32,185,4.812500
1405,"Great food, service and prices. I would recomm...",12,71,5.000000

## 1.4 Number of Stopwords

In [12]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

X_train['stopwords'] = X_train['text'].apply(lambda x: len([x for x in x.split() if x in stop]))
X_train[['text','stopwords']].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

                                                   text  stopwords
1221  The food is always good and reasonably priced....         11
1651  I am from NJ where I would enjoy pizza at leas...         20
1460  This place is great.  I love the ambiance (I'd...         21
1081  I never had bad service here but still going t...         11
1405  Great food, service and prices. I would recomm...          3

## 1.5 Number of Special Characters

In [15]:
X_train['hastags'] = X_train['text'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
X_train[['text','hastags']].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                                                   text  hastags
1221  The food is always good and reasonably priced....        0
1651  I am from NJ where I would enjoy pizza at leas...        0
1460  This place is great.  I love the ambiance (I'd...        0
1081  I never had bad service here but still going t...        0
1405  Great food, service and prices. I would recomm...        0

## 1.6 Number of numerics

In [16]:
X_train['numerics'] = X_train['text'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
X_train[['text','numerics']].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                                                   text  numerics
1221  The food is always good and reasonably priced....         0
1651  I am from NJ where I would enjoy pizza at leas...         0
1460  This place is great.  I love the ambiance (I'd...         1
1081  I never had bad service here but still going t...         0
1405  Great food, service and prices. I would recomm...         0

## 1.7 Number of Uppercase words

In [19]:
X_train['upper'] = X_train['text'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
X_train[['text','upper']].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                                                   text  upper
1221  The food is always good and reasonably priced....      0
1651  I am from NJ where I would enjoy pizza at leas...     11
1460  This place is great.  I love the ambiance (I'd...      2
1081  I never had bad service here but still going t...      2
1405  Great food, service and prices. I would recomm...      1

# 2. Basic Pre-processing

## 2.1 Lower case

In [24]:
X_train['text'] = X_train['text'].apply(lambda x: " ".join(x.lower() for x in x.split()))
X_train['text'].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

1221    the food is always good and reasonably priced....
1651    i am from nj where i would enjoy pizza at leas...
1460    this place is great. i love the ambiance (i'd ...
1081    i never had bad service here but still going t...
1405    great food, service and prices. i would recomm...
Name: text, dtype: object

## 2.2 Removing Punctuation

In [26]:
X_train['text'] = X_train['text'].str.replace('[^\w\s]','')
X_train['text'].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

1221    the food is always good and reasonably priced ...
1651    i am from nj where i would enjoy pizza at leas...
1460    this place is great i love the ambiance id rec...
1081    i never had bad service here but still going t...
1405    great food service and prices i would recommen...
Name: text, dtype: object

## 2.3 Removal of Stop Words

In [27]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
X_train['text'] = X_train['text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
X_train['text'].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

1221    food always good reasonably priced great place...
1651    nj would enjoy pizza least 34xs week moved cou...
1460    place great love ambiance id recommend sitting...
1081    never bad service still going make reservation...
1405    great food service prices would recommend plac...
Name: text, dtype: object

## 2.4 Common word removal

In [39]:
freq = pd.Series(' '.join(X_train['text']).split()).value_counts()[:10]

In [40]:
freq = list(freq.index)
X_train['text'] = X_train['text'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
X_train['text'].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

1221    always reasonably priced healthy meal looking ...
1651    nj would enjoy pizza least 34xs week moved cou...
1460    ambiance id recommend sitting one uppr levelst...
1081    never bad still going make reservation sometim...
1405                        prices would recommend anyone
Name: text, dtype: object

## 2.5 Rare words removal

In [45]:
freq = pd.Series(' '.join(X_train['text']).split()).value_counts()[-10:]

In [48]:
# freq

In [43]:
freq = list(freq.index)
X_train['text'] = X_train['text'].apply(lambda x: " ".join(x for x in x.split() if x not in freq))
X_train['text'].head()

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

1221    always reasonably priced healthy meal looking ...
1651    nj would enjoy pizza least 34xs week moved cou...
1460    ambiance id recommend sitting one uppr levelst...
1081    never bad still going make reservation sometim...
1405                        prices would recommend anyone
Name: text, dtype: object

## 2.6 Spelling Correction

In [50]:
from textblob import TextBlob
X_train['text'].apply(lambda x: str(TextBlob(x).correct()))

1221    always reasonably prices healthy meal looking ...
1651    no would enjoy penza least 34xs week moved cou...
1460    alliance id recommend sitting one upper levels...
1081    never bad still going make reservation sometim...
1405                        prices would recommend anyone
2798    first time eating five guns soon walked greete...
1430    wife hidden gem brest bar tender rich manager ...
984     in regular basis say special awesome definitel...
1227    cut seems like made date live music night amaz...
2320    purchased group deal visiting began located di...
522     knew branch dinner tonight blown away nicholas...
1974    server name tony wonderful first time ever goi...
2269    always awesome go quality meal your relative h...
944                    atmosphere staff friendly charming
2676    fresh bar atmosphere prices really prices terr...
569                 bad meal staff wonderful prices right
1232    really deal gros in detroit grew going greek f...
2198    got pad that pomegranate meat plate would defi...
2057    person write reviews restaurant always read ne...
825     loved new small quaint perfect definitely comi...
458     speaks pad that fish faces fantastic looking a...
1007    local coffee shop nice selection beer tap what...
894      org bomb thing dont like would move neighborhood
1755                             babel area fresh quality
1664    first time dinner pot roast mushroom burgher c...
1507    excellent staff portions large owners super ni...
2913                        raven awesome thing rainy day
2266    bluebeard pancake cheese awesome staff attenti...
918     awesome local spot brisker really others menti...
2020    wish could give 5 stars smaller places serve o...
                              ...
1971    hot sandwiched potatoes authentic vietnamese r...
1709    mexican town ever tried around corner work fel...
1214    environment fresh well prepared highly recomme...
310     now now now mummy beer julie wings clean holy ...
1346    happy stopped truck tonight truck caravan scot...
2340    cool hang friends vice indoors outdoor kind en...
128     vices feel dollar card far favorite restaurant...
1563    in pretty pick comes such rocks world super pi...
2027    new breakfast spot feel like home breakfast pe...
422
2270    always clean friendly local establishment wond...
551     excellent penza reasonably prices hidden gem f...
1981    got penza prices well always enjoyed friendly ...
1463    support local vendor like noble bread bacon ma...
2381    experience first time fast friendly would defi...
2828    boyfriend come always get quesadillas absolute...
1660    bar tender nice helpful wife went dinner order...
1331              went dinner dinner of really experience
2848    awesome unique favors staff incredibly friendl...
452     unfordable french gastro watson heart montreal...
1997    seriously penza arizona always fresh always cr...
361      awesome branch spot edges favors tried meatballs
943        penza olive oil cake perfect minor celebration
1720    far buffets began 1 2 types steamed order crab...
186     first time ever coming today would definitely ...
1144    absolutely kind loud simply pretty would defin...
2115     seated immediately fun meals comfortable seating
2281    katie server her fun always make experience to...
1245    excellent customer friendly staff brand new hi...
37      brick oven chicken 2 fried eggs top beginning ...
Name: text, Length: 1920, dtype: object

In [56]:
X_train.iloc[1][0]

'nj would enjoy pizza least 34xs week moved couldnt find anywhere near quality nj pizza metro girmaldis either kept hearing settebello joeys brooklyn pizza finally tried settebellos would well borough nyc nj strongly recomend'

## 2.7 Tokenization

In [59]:
TextBlob(X_train['text'][1]).words

KeyError: 0

## 2.8 Stemming

In [62]:
from nltk.stem import PorterStemmer
st = PorterStemmer()
X_train['text'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

1221    alway reason price healthi meal look tri walk ...
1651    nj would enjoy pizza least 34x week move could...
1460    ambianc id recommend sit one uppr levelsth rea...
1081    never bad still go make reserv sometim vibe wo...
1405                          price would recommend anyon
2798    first time eat five guy soon walk greet ask or...
1430    wife hidden gem brett bar tender rick manag co...
984     im regular basi say special awesom definit com...
1227    cute seem like made date live music night amz ...
2320    purchas groupon deal visit vega locat directli...
522     knew brunch dinner tonight blown away nichola ...
1974    server name toni wonder first time ever go ben...
2269    alway awesom go qualiti meal your rel hurri st...
944                        atmospher staff friendli charm
2676    fresh bar atmospher price realli price terrif ...
569                     bad meal staff wonder price right
1232    realli deal gyro im detroit grew go greek fami...
2198    got pad thai pomegran meat plate would definit...
2057    person write review restaur alway read never f...
825     love new small quaint perfect definit come lot...
458     steak pad thai fish taco fantast look authent ...
1007    local coffe shop nice select beer tap what lik...
894      omg bomb thing dont like would move neighborhood
1755                             bagel area fresh qualiti
1664    first time dinner pot roast mushroom burger ch...
1507    excel staff portion larg owner super nice atte...
2913                         ramen awesom thing raini day
2266    blueberri pancak chees awesom staff attent hel...
918     awesom local spot brisket realli other mention...
2020    wish could give 5 star smaller place serv oran...
                              ...
1971    hot sandwhich potato authent vietnames reason ...
1709    mexican town ever tri around corner work felt ...
1214           environ fresh well prepar highli recommend
310     wow wow wow yummi beer juciy wing clean holi c...
1346    happi stop truck tonight truck caravan scottsd...
2340    cool hang friend vibe indoor outdoor kind enjo...
128     vibe feel dollar card far favorit restaur vall...
1563    im pretti picki come sushi rock world super pi...
2027    new breakfast spot feel like home breakfast pe...
422
2270    alway clean friendli local eatablish wonderful...
551     excel pizza reason price hidden gem found quit...
1981    goto pizza price well alway enjoy friendli sta...
1463    support local vendor like nobl bread bacon mad...
2381    experi first time fast friendli would definit ...
2828    boyfriend come alway get quesadilla absolut su...
1660    bar tender nice help wife went dinner order so...
1331                  went dinner dinner gf realli experi
2848    awesom uniqu flavor staff incred friendli espe...
452     afford french bistro eatsin heart montrealru m...
1997    serious pizza arizona alway fresh alway crust ...
361            awesom brunch spot wedg flavor tri meatbal
943              pizza oliv oil cake perfect minor celebr
1720    far buffet vega 1 2 type steam order crab leg ...
186     first time ever come today would definit recom...
1144    absolut kind loud simpli pretti would definit ...
2115                    seat immedi fun meal comfort seat
2281    kati server sheri fun alway make experi top no...
1245    excel custom friendli staff brand new highli r...
37      brick oven chicken 2 fri egg top begin end dea...
Name: text, Length: 1920, dtype: object

In [63]:
# len(X_train)

1920

## 2.9 Lemmatization

In [67]:
from textblob import Word
X_train['text'] = X_train['text'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
X_train['text'].head(10)

/scratch/kc3172/py3tf/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

1221    always reasonably priced healthy meal looking ...
1651    nj would enjoy pizza least 34xs week moved cou...
1460    ambiance id recommend sitting one uppr levelst...
1081    never bad still going make reservation sometim...
1405                         price would recommend anyone
2798    first time eating five guy soon walked greeted...
1430    wife hidden gem brett bar tender rick manager ...
984     im regular basis say special awesome definitel...
1227    cute seems like made date live music night amz...
2320    purchased groupon deal visiting vega located d...
Name: text, dtype: object

# 3. Advance Text Processing

In [102]:
len(x)

1920

In [96]:
x = X_train.drop(['text'], axis=1)

In [97]:
from sklearn import svm
from sklearn import metrics

clf_svm = svm.SVC()
clf_svm.fit(x[:1000], y_train[:1000])

y_pred = clf_svm.predict(x[:1000])
acc = metrics.accuracy_score(y_train[:1000], y_pred)
print("Training score: {}".format(acc))

Training score: 0.933

In [105]:
y_pred = clf_svm.predict(x[:])
acc = metrics.accuracy_score(y_train[:], y_pred)
print("Training score: {}".format(acc))

Training score: 0.809375

In [84]:
y_train

array([0, 1, 1, ..., 1, 0, 1])

In [90]:
x

,text,word_count,char_count,avg_word,stopwords,hastags,numerics,upper
1651,nj would enjoy pizza least 34xs week moved cou...,72,353,4.338462,20,0,0,11
1460,ambiance id recommend sitting one uppr levelst...,60,316,4.508772,21,0,1,2
1081,never bad still going make reservation sometim...,32,185,4.812500,11,0,0,2
1405,price would recommend anyone,12,71,5.000000,3,0,0,1
2798,first time eating five guy soon walked greeted...,159,839,4.283019,62,0,1,9
1430,wife hidden gem brett bar tender rick manager ...,94,508,4.414894,38,0,0,2
984,im regular basis say special awesome definitel...,55,266,4.076923,25,0,1,2
1227,cute seems like made date live music night amz...,28,141,4.071429,9,0,0,0
2320,purchased groupon deal visiting vega located d...,51,276,4.431373,20,0,0,1
522,knew brunch dinner tonight blown away nicholas...,41,231,4.658537,16,0,0,1
1974,server name tony wonderful first time ever goi...,53,242,3.584906,27,0,0,4
2269,always awesome go quality meal youre relative ...,108,571,4.296296,50,0,0,4
944,atmosphere staff friendly charming,11,68,5.272727,4,0,0,0
2676,fresh bar atmosphere price really price terrif...,39,204,4.256410,17,0,0,0
569,bad meal staff wonderful price right,22,100,3.761905,10,0,0,1
1232,really deal gyro im detroit grew going greek f...,38,201,4.315789,13,0,0,1
2198,got pad thai pomegranate meat plate would defi...,23,125,4.478261,7,0,0,2
2057,person write review restaurant always read nev...,152,742,4.251799,56,0,0,4
825,loved new small quaint perfect definitely comi...,33,184,4.606061,11,0,0,0
458,steak pad thai fish taco fantastic looking aut...,36,187,4.222222,16,0,0,0
1007,local coffee shop nice selection beer tap what...,39,195,4.025641,17,0,0,1
894,omg bomb thing dont like would move neighborhood,20,96,3.850000,10,0,0,3
1755,bagel area fresh quality,13,64,4.000000,5,0,0,0
1664,first time dinner pot roast mushroom burger ch...,31,197,5.387097,5,0,0,0
1507,excellent staff portion large owner super nice...,20,119,5.000000,7,0,0,0
2913,ramen awesome thing rainy day,11,61,4.636364,3,0,0,0
2266,blueberry pancake cheese awesome staff attenti...,41,225,4.868421,18,0,0,1
918,awesome local spot brisket really others menti...,36,202,4.771429,13,0,0,0
2020,wish could give 5 star smaller place serve ora...,39,207,4.447368,8,0,1,2
1726,shrimp cocktail house gumbo always layer flavo...,18,106,4.944444,5,0,0,0
...,...,...,...,...,...,...,...,...
1971,hot sandwhiches potato authentic vietnamese re...,101,569,4.737374,38,0,0,3
1709,mexican town ever tried around corner work fel...,34,164,3.852941,14,0,0,1
1214,environment fresh well prepared highly recomme...,12,74,6.300000,2,0,0,0
310,wow wow wow yummy beer juciy wing clean holy c...,23,128,4.608696,7,0,0,0
1346,happy stopped truck tonight truck caravan scot...,57,279,4.372549,18,0,0,1
2340,cool hang friend vibe indoors outdoors kind en...,83,391,4.544118,30,0,0,1
128,vibe feel dollar card far favorite restaurant ...,43,223,4.209302,19,0,0,1
1563,im pretty picky come sushi rock world super pi...,57,310,4.456140,24,0,0,0
2027,new breakfast spot feel like home breakfast pe...,27,145,4.407407,9,0,0,1
422,,13,64,4.000000,6,0,0,0
2270,always clean friendly local eatablishment wond...,25,158,5.360000,10,0,0,0
551,excellent pizza reasonably priced hidden gem f...,51,268,4.274510,22,0,0,1
1981,goto pizza price well always enjoyed friendly ...,30,168,4.633333,10,0,0,1
1463,support local vendor like noble bread bacon ma...,25,163,5.560000,6,0,0,0
2381,experience first time fast friendly would defi...,27,150,4.592593,7,0,0,2
2828,boyfriend come always get quesadilla absolutel...,32,178,4.593750,14,0,0,1
1660,bar tender nice helpful wife went dinner order...,39,205,4.394737,18,0,0,2
1331,went dinner dinner gf really experience,14,73,4.285714,7,0,0,0
2848,awesome unique flavor staff incredibly friendl...,30,182,5.100000,9,0,0,1
452,affordable french bistro eatsin heart montreal...,209,1220,4.842105,79,0,0,6
1997,seriously pizza arizona always fresh always cr...,24,140,4.875000,7,0,0,0
361,awesome brunch spot wedge flavor tried meatball,14,81,4.857143,5,0,0,1
943,pizza olive oil cake perfect minor celebration,15,86,4.800000,4,0,0,0
1720,far buffet vega 1 2 type steamed order crab le...,88,462,4.310345,32,0,1,0
186,first time ever coming today would definitely ...,183,897,3.928571,85,0,2,4
1144,absolutely kind loud simply pretty would defin...,25,147,4.920000,7,0,0,1
2115,seated immediately fun meal comfortable seating,15,96,5.466667,5,0,0,0
2281,katie server sheri fun always make experience ...,34,162,3.794118,14,0,1,2
1245,excellent customer friendly staff brand new hi...,40,240,5.025000,15,0,0,0
37,brick oven chicken 2 fried egg top beginning e...,42,222,4.414634,11,0,1,7